"""Render and write Markdown Role-to-Roadmap outputs."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def _bullets(items: list[str]) -> str:
    if not items:
        return "_None listed._"
    return "\n".join(f"- {item}" for item in items)


def render_markdown(contract: dict[str, Any], *, job_source: str, profile_source: str) -> str:
    role = contract["role_interpretation"]
    bg = contract["candidate_background_translation"]
    first = contract["first_investigation_prompt"]
    evidence = contract["evidence_plan"]
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    problems = "\n\n".join(
        f"### {i}. {item['problem']}\n"
        f"- **Why company pays for it:** {item['why_company_pays_for_it']}\n"
        f"- **Constraints:** {', '.join(item['constraints']) if item['constraints'] else '_none_'}\n"
        f"- **Failure modes:**\n{_bullets(item['failure_modes'])}\n"
        f"- **JD evidence:** {item['jd_evidence']}"
        for i, item in enumerate(contract["expensive_problem_map"], start=1)
    )

    keywords = "\n\n".join(
        f"### `{item['surface_keyword']}` → {item['deep_skill_or_principle']}\n"
        f"- **Why it matters:** {item['why_it_matters']}\n"
        f"- **Danger of learning in isolation:** {item['danger_of_learning_it_in_isolation']}"
        for item in contract["surface_keywords_vs_deep_skills"]
    )

    strengths = "\n\n".join(
        f"### {item['strength']}\n"
        f"- **Profile anchor:** {item['profile_anchor']}\n"
        f"- **Role relevance:** {item['role_relevance']}"
        for item in bg["transferable_strengths"]
    )

    gaps = "\n\n".join(
        f"### Gap: {item['gap']}\n"
        f"- **Why it blocks credibility:** {item['why_it_blocks_credibility']}\n"
        f"- **Learn first instead:** {item['first_thing_to_learn_instead']}"
        for item in bg["real_gaps"]
    )

    threshold = "\n\n".join(
        f"### [{item['capability_scope']}] {item['capability']}\n"
        f"- **Why it matters generally:** {item['why_it_matters_generally']}\n"
        f"- **Connected role problem:** {item['connected_role_problem']}\n"
        f"- **Evidence that proves it:** {item['evidence_that_proves_it']}"
        for item in contract["general_value_threshold"]
    )

    deps = "\n\n".join(
        f"### {i}. {item['skill_or_model']}\n"
        f"- **Depends on:** {', '.join(item['depends_on']) if item['depends_on'] else '_none_'}\n"
        f"- **Unlocks:** {', '.join(item['unlocks']) if item['unlocks'] else '_none_'}\n"
        f"- **Why before later work:** {item['why_it_comes_before_later_work']}"
        for i, item in enumerate(contract["skill_dependency_graph"], start=1)
    )

    roadmap = "\n\n".join(
        f"### Investigation {i}: {item['title']}\n"
        f"**Expensive problem:** {item['expensive_problem']}\n\n"
        f"**Engineering question:** {item['engineering_question']}\n\n"
        f"**Mental model to build:** {item['mental_model_to_build']}\n\n"
        f"**Principles**\n{_bullets(item['principles'])}\n\n"
        f"**Technologies introduced**\n{_bullets(item['technologies_introduced'])}\n\n"
        f"**Observe existing system:** {item['observe_existing_system']}\n\n"
        f"**Build or modify:** {item['build_or_modify']}\n\n"
        f"**Break / debug / improve:** {item['break_debug_improve']}\n\n"
        f"**Evidence output:** {item['evidence_output']}\n\n"
        f"**Builds on prior artifact:** {item['builds_on_prior_artifact']}\n\n"
        f"**Artifact this investigation produces:** {item['artifact_this_investigation_produces']}\n\n"
        f"**Why this comes now:** {item['why_this_comes_now']}"
        for i, item in enumerate(contract["investigation_roadmap"], start=1)
    )

    ladder = "\n\n".join(
        f"### Level {item['level']}: {item['title']}\n"
        f"- **Same system:** `{item['same_system_name']}`\n"
        f"- **Extends previous:** {item['extends_previous_level']}\n"
        f"- **Proves:** {item['proves']}\n"
        f"- **Scope:** {item['scope']}\n"
        f"- **Evidence:**\n{_bullets(item['evidence'])}\n"
        f"- **Why not before prerequisites:** {item['why_not_before_prerequisites']}\n"
        f"- **Connected investigations:** {', '.join(item['connected_investigations'])}"
        for item in sorted(contract["proof_of_work_ladder"], key=lambda x: x["level"])
    )

    interviews = "\n\n".join(
        f"### {item['expectation']}\n"
        f"- **Current readiness:** {item['current_readiness']}\n"
        f"- **Evidence needed:** {item['evidence_needed']}\n"
        f"- **Likely interview challenge:** {item['likely_interview_challenge']}\n"
        f"- **How to answer after roadmap:** {item['how_to_answer_after_roadmap']}"
        for item in contract["interview_readiness_map"]
    )

    return f"""# Role-to-Roadmap

_Generated by Project Lambda · {generated_at}_  
_Job source:_ `{job_source}` · _Profile source:_ `{profile_source}`

## 1. Role interpretation

**{role['one_liner']}**

**Real mission:** {role['real_mission']}

**What success looks like:** {role['what_success_looks_like']}

**What this role is not**
{_bullets(role['what_this_role_is_not'])}

## 2. Expensive problem map

{problems}

## 3. Surface keywords vs deep skills

{keywords}

## 4. Candidate background translation

### Transferable strengths

{strengths}

### Real gaps

{gaps}

### Misleading overclaims to avoid

{_bullets(bg['misleading_overclaims_to_avoid'])}

### Strongest positioning angle

{bg['strongest_positioning_angle']}

## 5. General value threshold

{threshold}

## 6. Skill dependency graph

{deps}

## 7. Investigation roadmap

{roadmap}

## 8. Proof-of-work ladder

{ladder}

## 9. First investigation prompt

**Expensive problem:** {first['expensive_problem']}

**Engineering question:** {first['engineering_question']}

**Phase 0 mental model:** {first['phase_0_mental_model']}

**Dependency layers**
{_bullets(first['dependency_layers'])}

**Subquestions**
{_bullets(first['subquestions'])}

**Visual resources / search prompts**
{_bullets(first['visual_resources_or_search_prompts'])}

**Observe / build / improve / evidence plan:** {first['observe_build_improve_evidence_plan']}

**Reflection question:** {first['reflection_question']}

### Ready to paste

```text
{first['ready_to_paste_prompt']}
```

## 10. Evidence plan

**Obsidian pages**
{_bullets(evidence['obsidian_pages'])}

**GitHub repos or folders**
{_bullets(evidence['github_repos_or_folders'])}

**Diagrams**
{_bullets(evidence['diagrams'])}

**Benchmarks or logs**
{_bullets(evidence['benchmarks_or_logs'])}

**README sections**
{_bullets(evidence['readme_sections'])}

**Interview artifacts**
{_bullets(evidence['interview_artifacts'])}

## 11. Interview readiness map

{interviews}
"""


def default_output_path(outputs_dir: Path, stem: str = "roadmap") -> Path:
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    return outputs_dir / f"{stem}_{stamp}.md"


def write_markdown(markdown: str, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(markdown, encoding="utf-8")
    return path
