"""Render and write Markdown Problem-Solution Contracts."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def _bullets(items: list[str]) -> str:
    if not items:
        return "_None listed._"
    return "\n".join(f"- {item}" for item in items)


def _yes_no(value: bool) -> str:
    return "yes" if value else "no"


def render_markdown(contract: dict[str, Any], *, job_source: str, profile_source: str) -> str:
    role = contract["role_truth"]
    signature = contract["role_specific_problem_signature"]
    bg = contract["candidate_background_translation"]
    pow_ = contract["proof_of_work_project"]
    design = pow_["design_constraints"]
    artifacts = contract["evidence_artifacts"]
    review = contract["staff_engineer_review"]
    summary = contract["problem_solution_contract_summary"]
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    rejected = "\n\n".join(
        f"### Rejected: {item['generic_interpretation']}\n"
        f"**Why insufficient:** {item['why_insufficient']}"
        for item in contract["rejected_generic_interpretations"]
    )

    hidden = "\n\n".join(
        f"### {i}. {item['problem']}\n"
        f"- **Why it matters:** {item['why_it_matters']}\n"
        f"- **Likely failure mode:** {item['likely_failure_mode']}\n"
        f"- **Why not generic:** {item['why_not_generic']}\n"
        f"- **Evidence basis:** {item['evidence_basis']}"
        for i, item in enumerate(contract["hidden_engineering_problems"], start=1)
    )

    constraints = "\n".join(
        f"- **{item['constraint']}** _(source: {item['source']})_"
        for item in contract["constraints"]
    ) or "_None listed._"

    tradeoffs = "\n\n".join(
        f"### {item['axis']}\n"
        f"- **A:** {item['choice_a']}\n"
        f"- **B:** {item['choice_b']}\n"
        f"- **Recommendation:** {item['recommendation']}\n"
        f"- **Why this axis matters here:** {item['why_this_axis_matters_here']}"
        for item in contract["tradeoffs"]
    )

    performance = "\n".join(
        f"- **{item['metric_or_bar']}** — {item['why_it_exists']} "
        f"_Demonstrate by:_ {item['how_to_demonstrate']} "
        f"_(source: {item['source']})_"
        for item in contract["performance_expectations"]
    )

    strengths = "\n\n".join(
        f"### {item['strength']}\n"
        f"- **Profile anchor:** {item['profile_anchor']}\n"
        f"- **Role relevance:** {item['role_relevance']}"
        for item in bg["role_relevant_strengths"]
    )

    honest_gaps = "\n".join(
        f"- **{item['gap']}** — {item['why_it_matters_for_this_role']}"
        for item in bg["honest_gaps"]
    )

    gaps = "\n\n".join(
        f"### Gap: {item['gap']}\n"
        f"- **Evidence that closes it:** {item['evidence_that_would_close_it']}\n"
        f"- **Profile relevance:** {item['profile_relevance']}"
        for item in contract["missing_proof_of_capability"]
    )

    checklist = "\n".join(
        f"- [ ] **{item['check']}**\n"
        f"  - Verify: {item['how_to_verify']}\n"
        f"  - Pass if: {item['pass_condition']}"
        for item in contract["verification_checklist"]
    )

    sm = pow_["state_machine"]
    transitions = "\n".join(
        f"- `{t['from_state']}` → `{t['to_state']}` "
        f"({t['path_type']}) — {t['trigger']}"
        for t in sm["transitions"]
    ) or "_None listed._"

    hw = pow_["hardware_management_simulation"]
    ops_metrics = "\n".join(
        f"- **{m['metric']}** — {m['definition']} "
        f"_Measure by:_ {m['how_measured_in_project']} "
        f"_(source: {m['source']})_"
        for m in pow_["proposed_ops_metrics"]
    )
    auto = pow_["automation_boundaries"]
    ops = pow_["operational_model"]

    return f"""# Problem-Solution Contract

_Generated by Project Lambda · {generated_at}_  
_Job source:_ `{job_source}` · _Profile source:_ `{profile_source}`

## 1. What this job is really about

**{role['one_liner']}**

{role['mission']}

**What success looks like:** {role['what_success_looks_like']}

## 2. Rejected generic interpretations

{rejected}

## 3. Role-specific problem signature

{_bullets(signature['signature_statements'])}

- **Primary failure domain:** {signature['primary_failure_domain']}
- **Ownership boundary:** {signature['ownership_boundary']}
- **What must become a system:** {signature['what_must_become_a_system']}

## 4. Surface keywords

{_bullets(contract['surface_keywords'])}

## 5. Hidden engineering problems

{hidden}

## 6. Constraints

{constraints}

## 7. Tradeoffs

{tradeoffs}

## 8. Performance expectations

{performance}

## 9. Candidate background translation

### Role-relevant strengths

{strengths}

### Transferable patterns

{_bullets(bg['transferable_patterns'])}

### Honest gaps

{honest_gaps}

### Must not claim

{_bullets(bg['what_must_not_be_claimed'])}

## 10. Missing proof of capability

{gaps}

## 11. Proof-of-work project

### {pow_['title']}

**Problem statement:** {pow_['problem_statement']}

**Scope:** {pow_['scope']}

**Why this project:** {pow_['why_this_project']}

**Timebox:** {pow_['timebox']}

**Non-goals**
{_bullets(pow_['non_goals'])}

**Suggested stack**
{_bullets(pow_['tech_stack_suggestion'])}

**Deliverables**
{_bullets(pow_['deliverables'])}

**Success criteria**
{_bullets(pow_['success_criteria'])}

### Operational model

- **Observed:** {ops['what_is_observed']}
- **Decision:** {ops['what_decision_is_made']}
- **Action:** {ops['what_action_is_taken']}
- **Recovery verified by:** {ops['how_recovery_is_verified']}
- **Escalate humans when:** {ops['when_humans_are_escalated']}

### Automation boundaries

- **Why not absolute full automation:** {auto['why_not_full_automation']}

**Automated common paths**
{_bullets(auto['automated_common_paths'])}

**Human escalation paths**
{_bullets(auto['human_escalation_paths'])}

**Unsafe / ambiguous states**
{_bullets(auto['unsafe_or_ambiguous_states'])}

**Manual approval gates**
{_bullets(auto['manual_approval_gates'])}

### State machine

- **Required for this role:** {_yes_no(sm['required_for_this_role'])}
- **Rationale:** {sm['rationale']}

**States**
{_bullets(sm['states'])}

**Happy path**
{_bullets(sm['happy_path'])}

**Transitions**
{transitions}

**Terminal states**
{_bullets(sm['terminal_states'])}

### Hardware management simulation

- **Required by JD:** {_yes_no(hw['required_by_jd'])}
- **JD signals:** {', '.join(hw['jd_signals']) or '_none_'}
- **Mocked API / telemetry:** {hw['mocked_api_or_telemetry_source']}
- **Intentionally not real:** {hw['what_is_intentionally_not_real']}

**Example endpoints / signals**
{_bullets(hw['example_endpoints_or_signals'])}

### Proposed ops metrics

{ops_metrics}

### Design constraints

- **Local-first:** {_yes_no(design['local_first'])}
- **Simulated when needed:** {_yes_no(design['simulated_when_needed'])}
- **Includes failure injection:** {_yes_no(design['includes_failure_injection'])}
- **Includes verification checklist:** {_yes_no(design['includes_verification_checklist'])}
- **Required outputs:** {', '.join(design['required_outputs'])}

**Simulation strategy:** {pow_['simulation_strategy']}

**Failure injection plan**
{_bullets(pow_['failure_injection_plan'])}

## 12. Evidence artifacts

- **GitHub repo:** {artifacts['github_repo']}
- **README:** {artifacts['readme']}
- **Architecture diagram:** {artifacts['architecture_diagram']}
- **Failure mode table:** {artifacts['failure_mode_table']}
- **Verification log:** {artifacts['verification_log']}
- **Benchmark / measurement output:** {artifacts['benchmark_or_measurement_output']}
- **Postmortem / incident note:** {artifacts['postmortem_or_incident_note']}
- **Two-minute interview explanation:** {artifacts['two_minute_interview_explanation']}

## 13. Verification / benchmark checklist

{checklist}

## 14. Staff engineer review

- **Credible?** {_yes_no(review['is_credible'])} — {review['credibility_rationale']}
- **What makes it credible:** {review['what_makes_it_credible']}
- **What could make it look toy:** {review['what_could_make_it_look_toy']}
- **One hiring-manager-relevant change:** {review['one_change_for_hiring_manager_relevance']}
- **Too broad?** {_yes_no(review['is_too_broad'])} — {review['scope_diagnosis']}

**How to make it higher signal**
{_bullets(review['how_to_make_higher_signal'])}

**Hiring manager challenges**
{_bullets(review['hiring_manager_challenges'])}

## 15. Problem-Solution Contract (summary)

**Problem:** {summary['problem']}

**Proposed solution shape:** {summary['proposed_solution_shape']}

**Non-goals**
{_bullets(summary['non_goals'])}

**Risks**
{_bullets(summary['risks'])}
"""


def default_output_path(outputs_dir: Path, stem: str = "contract") -> Path:
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    return outputs_dir / f"{stem}_{stamp}.md"


def write_markdown(markdown: str, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(markdown, encoding="utf-8")
    return path
